export enum tagTypes {
  customer = "customer",
  admin = "admin",
  superadmin = "superadmin",
  auth = "auth",
  user = "user",
  category = "category",
  service = "service",
  bookings = "bookings",
  blog = "blog",
  faq = "faq",
  cart = "cart",
  review = "review",
  feedback = "feedback",
}

export const tagTypesList = [
  tagTypes.admin,
  tagTypes.customer,
  tagTypes.superadmin,
  tagTypes.auth,
  tagTypes.user,
  tagTypes.category,
  tagTypes.service,
  tagTypes.bookings,
  tagTypes.blog,
  tagTypes.faq,
  tagTypes.cart,
  tagTypes.review,
  tagTypes.feedback,
];
